# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e42dc33507a4f015ae91ae31343b9c07b932a3880bd8cfff08b0ea165fedc153eadd5534fe093c3e3ff1d6e91a2c5527c843998ce65a6c1217d98e5da8b0496

test:
  secret_key_base: b5c904916e72bc1d5a31d6afa00df31959095c0f2dc79be95e85604fee54bb68fffed887016ca74a9cef83215593c7a5cc9eb787215e0145f5daeb533b0da81e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
